_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 3b059288-ae39-41f1-a88d-151860f548da
name: 'Kyriarch Engineering and Trading Corporation'
mail: timothy@kyriarch.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
